### ISSUE TITLE
Query on localization

### ISSUE THREAD

**Issue by thealchemist-x** [yuyang-huang/keras-inception-resnet-v2#1]
Hi all, 

I'm wondering does this network comes with some sort of RPN for localization of the object purposes? Also, is it possible to train customized datasets in this repo?

Thanks for reading :)

**Comment by yuyang-huang** [comment]
No, this network is for image classification, as described in the paper: https://arxiv.org/abs/1602.07261
Training this kind of large model from scratch is rather difficult, but of course you can try to fine-tune this model with your own dataset. You can find examples on [Keras documentation](https://keras.io/applications/).
