### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by SuperYm** [yuyang-huang/keras-inception-resnet-v2#3]
When i finetuning on another 5-class dataset, error like that:
  tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,35,35,320]
	 [[Node: Block35_6_ScaleSum/add = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Block35_5_Activation/Relu, Block35_6_ScaleSum/mul)]]
	 [[Node: loss/mul/_8119 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_78226_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
I use GTX 1050Ti with 4G Memory or 1080 with 8G Memory,but the same error.i don't know why?

**Comment by yuyang-huang** [comment]
What's the size of your images? From my own experience I'll say that for a GPU with 8G memory, `batch_size=32` may be too large. I use `batch_size=20` on a 11G K80 GPU with images resized to `(299, 299)` when finetuning this model.

**Comment by SuperYm** [comment]
thanks,bacth_size=20  is ok!
