### ISSUE TITLE
List Index out of Range:extract_weights.py

### ISSUE THREAD

**Issue by nandy1994** [yuyang-huang/keras-inception-resnet-v2#6]
Hi,
I am trying to convert my ckpt weights into hd5 model. Before that, I was executing your code to obtain weights(.npy) and ckpt version of inception_resnet. When i execute the code - extract_weights.py, I am getting an error called "LIST INDEX OUT OF RANGE"

Error Message:
IndexErrorTraceback (most recent call last)
<ipython-input-12-e52ddb91ef97> in <module>
     80     cache_dir=MODEL_DIR)
     81 
---> 82 checkpoint_file = glob(os.path.join(MODEL_DIR, 'inception_resnet_v2_*.ckpt'))[0]
     83 extract_tensors_from_checkpoint_file(checkpoint_file)

IndexError: list index out of range

Please help me out as soon as possible.

**Comment by yuyang-huang** [comment]
It's because the `MODEL_DIR` was not automatically created.

Added a line to create `MODEL_DIR` in `extract_weights.py`. It should be fixed now.

**Comment by bcrevath** [comment]
Thanks a lot Yuyang. It works fine now.
